inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/dummy_app/bin/**/*'
    - 'spec/dummy_app/db/schema.rb'
    - 'spec/dummy_app/tmp/**/*'
    - 'vendor/bundle/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 69.98 # TODO: Lower to 15

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Max: 120 # TODO: Lower to 100

Metrics/CyclomaticComplexity:
  Max: 12 # TODO: Lower to 6

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 29 # TODO: Lower to 15

Metrics/ModuleLength:
  Max: 200 # TODO: Lower to 100

Metrics/ParameterLists:
  Max: 8 # TODO: Lower to 4
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 14 # TODO: Lower to 7

Naming/FileName:
  Exclude:
    - 'lib/rails_admin/bootstrap-sass.rb'

Style/Alias:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'
