# fly.toml app configuration file generated for rails-admin on 2023-08-06T18:22:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-admin"
primary_region = "iad"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
